#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps_fpga' in
 * file './hps_fpga.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'matrix_write_en', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_WRITE_EN_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_WRITE_EN_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_WRITE_EN_COMPONENT_NAME matrix_write_en
#define MATRIX_WRITE_EN_BASE 0x0
#define MATRIX_WRITE_EN_SPAN 16
#define MATRIX_WRITE_EN_END 0xf
#define MATRIX_WRITE_EN_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_WRITE_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_WRITE_EN_CAPTURE 0
#define MATRIX_WRITE_EN_DATA_WIDTH 31
#define MATRIX_WRITE_EN_DO_TEST_BENCH_WIRING 0
#define MATRIX_WRITE_EN_DRIVEN_SIM_VALUE 0
#define MATRIX_WRITE_EN_EDGE_TYPE NONE
#define MATRIX_WRITE_EN_FREQ 50000000
#define MATRIX_WRITE_EN_HAS_IN 0
#define MATRIX_WRITE_EN_HAS_OUT 1
#define MATRIX_WRITE_EN_HAS_TRI 0
#define MATRIX_WRITE_EN_IRQ_TYPE NONE
#define MATRIX_WRITE_EN_RESET_VALUE 0

/*
 * Macros for device 'matrix_write_data', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_WRITE_DATA_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_WRITE_DATA_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_WRITE_DATA_COMPONENT_NAME matrix_write_data
#define MATRIX_WRITE_DATA_BASE 0x10
#define MATRIX_WRITE_DATA_SPAN 16
#define MATRIX_WRITE_DATA_END 0x1f
#define MATRIX_WRITE_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_WRITE_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_WRITE_DATA_CAPTURE 0
#define MATRIX_WRITE_DATA_DATA_WIDTH 32
#define MATRIX_WRITE_DATA_DO_TEST_BENCH_WIRING 0
#define MATRIX_WRITE_DATA_DRIVEN_SIM_VALUE 0
#define MATRIX_WRITE_DATA_EDGE_TYPE NONE
#define MATRIX_WRITE_DATA_FREQ 50000000
#define MATRIX_WRITE_DATA_HAS_IN 0
#define MATRIX_WRITE_DATA_HAS_OUT 1
#define MATRIX_WRITE_DATA_HAS_TRI 0
#define MATRIX_WRITE_DATA_IRQ_TYPE NONE
#define MATRIX_WRITE_DATA_RESET_VALUE 0

/*
 * Macros for device 'matrix_write_addr', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_WRITE_ADDR_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_WRITE_ADDR_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_WRITE_ADDR_COMPONENT_NAME matrix_write_addr
#define MATRIX_WRITE_ADDR_BASE 0x20
#define MATRIX_WRITE_ADDR_SPAN 16
#define MATRIX_WRITE_ADDR_END 0x2f
#define MATRIX_WRITE_ADDR_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_WRITE_ADDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_WRITE_ADDR_CAPTURE 0
#define MATRIX_WRITE_ADDR_DATA_WIDTH 32
#define MATRIX_WRITE_ADDR_DO_TEST_BENCH_WIRING 0
#define MATRIX_WRITE_ADDR_DRIVEN_SIM_VALUE 0
#define MATRIX_WRITE_ADDR_EDGE_TYPE NONE
#define MATRIX_WRITE_ADDR_FREQ 50000000
#define MATRIX_WRITE_ADDR_HAS_IN 0
#define MATRIX_WRITE_ADDR_HAS_OUT 1
#define MATRIX_WRITE_ADDR_HAS_TRI 0
#define MATRIX_WRITE_ADDR_IRQ_TYPE NONE
#define MATRIX_WRITE_ADDR_RESET_VALUE 0

/*
 * Macros for device 'matrix_dims', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_DIMS_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_DIMS_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_DIMS_COMPONENT_NAME matrix_dims
#define MATRIX_DIMS_BASE 0x30
#define MATRIX_DIMS_SPAN 16
#define MATRIX_DIMS_END 0x3f
#define MATRIX_DIMS_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_DIMS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_DIMS_CAPTURE 0
#define MATRIX_DIMS_DATA_WIDTH 32
#define MATRIX_DIMS_DO_TEST_BENCH_WIRING 0
#define MATRIX_DIMS_DRIVEN_SIM_VALUE 0
#define MATRIX_DIMS_EDGE_TYPE NONE
#define MATRIX_DIMS_FREQ 50000000
#define MATRIX_DIMS_HAS_IN 0
#define MATRIX_DIMS_HAS_OUT 1
#define MATRIX_DIMS_HAS_TRI 0
#define MATRIX_DIMS_IRQ_TYPE NONE
#define MATRIX_DIMS_RESET_VALUE 0

/*
 * Macros for device 'matrix_cycles', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_CYCLES_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_CYCLES_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_CYCLES_COMPONENT_NAME matrix_cycles
#define MATRIX_CYCLES_BASE 0x40
#define MATRIX_CYCLES_SPAN 16
#define MATRIX_CYCLES_END 0x4f
#define MATRIX_CYCLES_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_CYCLES_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_CYCLES_CAPTURE 0
#define MATRIX_CYCLES_DATA_WIDTH 32
#define MATRIX_CYCLES_DO_TEST_BENCH_WIRING 0
#define MATRIX_CYCLES_DRIVEN_SIM_VALUE 0
#define MATRIX_CYCLES_EDGE_TYPE NONE
#define MATRIX_CYCLES_FREQ 50000000
#define MATRIX_CYCLES_HAS_IN 1
#define MATRIX_CYCLES_HAS_OUT 0
#define MATRIX_CYCLES_HAS_TRI 0
#define MATRIX_CYCLES_IRQ_TYPE NONE
#define MATRIX_CYCLES_RESET_VALUE 0

/*
 * Macros for device 'matrix_data', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_DATA_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_DATA_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_DATA_COMPONENT_NAME matrix_data
#define MATRIX_DATA_BASE 0x50
#define MATRIX_DATA_SPAN 16
#define MATRIX_DATA_END 0x5f
#define MATRIX_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_DATA_CAPTURE 0
#define MATRIX_DATA_DATA_WIDTH 32
#define MATRIX_DATA_DO_TEST_BENCH_WIRING 0
#define MATRIX_DATA_DRIVEN_SIM_VALUE 0
#define MATRIX_DATA_EDGE_TYPE NONE
#define MATRIX_DATA_FREQ 50000000
#define MATRIX_DATA_HAS_IN 1
#define MATRIX_DATA_HAS_OUT 0
#define MATRIX_DATA_HAS_TRI 0
#define MATRIX_DATA_IRQ_TYPE NONE
#define MATRIX_DATA_RESET_VALUE 0

/*
 * Macros for device 'matrix_status', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_STATUS_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_STATUS_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_STATUS_COMPONENT_NAME matrix_status
#define MATRIX_STATUS_BASE 0x60
#define MATRIX_STATUS_SPAN 16
#define MATRIX_STATUS_END 0x6f
#define MATRIX_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_STATUS_CAPTURE 0
#define MATRIX_STATUS_DATA_WIDTH 32
#define MATRIX_STATUS_DO_TEST_BENCH_WIRING 0
#define MATRIX_STATUS_DRIVEN_SIM_VALUE 0
#define MATRIX_STATUS_EDGE_TYPE NONE
#define MATRIX_STATUS_FREQ 50000000
#define MATRIX_STATUS_HAS_IN 1
#define MATRIX_STATUS_HAS_OUT 0
#define MATRIX_STATUS_HAS_TRI 0
#define MATRIX_STATUS_IRQ_TYPE NONE
#define MATRIX_STATUS_RESET_VALUE 0

/*
 * Macros for device 'matrix_index', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_INDEX_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_INDEX_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_INDEX_COMPONENT_NAME matrix_index
#define MATRIX_INDEX_BASE 0x70
#define MATRIX_INDEX_SPAN 16
#define MATRIX_INDEX_END 0x7f
#define MATRIX_INDEX_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_INDEX_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_INDEX_CAPTURE 0
#define MATRIX_INDEX_DATA_WIDTH 6
#define MATRIX_INDEX_DO_TEST_BENCH_WIRING 0
#define MATRIX_INDEX_DRIVEN_SIM_VALUE 0
#define MATRIX_INDEX_EDGE_TYPE NONE
#define MATRIX_INDEX_FREQ 50000000
#define MATRIX_INDEX_HAS_IN 0
#define MATRIX_INDEX_HAS_OUT 1
#define MATRIX_INDEX_HAS_TRI 0
#define MATRIX_INDEX_IRQ_TYPE NONE
#define MATRIX_INDEX_RESET_VALUE 0

/*
 * Macros for device 'matrix_ctrl', class 'altera_avalon_pio'
 * The macros are prefixed with 'MATRIX_CTRL_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_CTRL_COMPONENT_TYPE altera_avalon_pio
#define MATRIX_CTRL_COMPONENT_NAME matrix_ctrl
#define MATRIX_CTRL_BASE 0x80
#define MATRIX_CTRL_SPAN 16
#define MATRIX_CTRL_END 0x8f
#define MATRIX_CTRL_BIT_CLEARING_EDGE_REGISTER 0
#define MATRIX_CTRL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MATRIX_CTRL_CAPTURE 0
#define MATRIX_CTRL_DATA_WIDTH 32
#define MATRIX_CTRL_DO_TEST_BENCH_WIRING 0
#define MATRIX_CTRL_DRIVEN_SIM_VALUE 0
#define MATRIX_CTRL_EDGE_TYPE NONE
#define MATRIX_CTRL_FREQ 50000000
#define MATRIX_CTRL_HAS_IN 0
#define MATRIX_CTRL_HAS_OUT 1
#define MATRIX_CTRL_HAS_TRI 0
#define MATRIX_CTRL_IRQ_TYPE NONE
#define MATRIX_CTRL_RESET_VALUE 0

/*
 * Macros for device 'sw', class 'altera_avalon_pio'
 * The macros are prefixed with 'SW_'.
 * The prefix is the slave descriptor.
 */
#define SW_COMPONENT_TYPE altera_avalon_pio
#define SW_COMPONENT_NAME sw
#define SW_BASE 0x90
#define SW_SPAN 16
#define SW_END 0x9f
#define SW_BIT_CLEARING_EDGE_REGISTER 0
#define SW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SW_CAPTURE 0
#define SW_DATA_WIDTH 10
#define SW_DO_TEST_BENCH_WIRING 0
#define SW_DRIVEN_SIM_VALUE 0
#define SW_EDGE_TYPE NONE
#define SW_FREQ 50000000
#define SW_HAS_IN 1
#define SW_HAS_OUT 0
#define SW_HAS_TRI 0
#define SW_IRQ_TYPE NONE
#define SW_RESET_VALUE 0

/*
 * Macros for device 'led', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_'.
 * The prefix is the slave descriptor.
 */
#define LED_COMPONENT_TYPE altera_avalon_pio
#define LED_COMPONENT_NAME led
#define LED_BASE 0xa0
#define LED_SPAN 16
#define LED_END 0xaf
#define LED_BIT_CLEARING_EDGE_REGISTER 0
#define LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_CAPTURE 0
#define LED_DATA_WIDTH 10
#define LED_DO_TEST_BENCH_WIRING 0
#define LED_DRIVEN_SIM_VALUE 0
#define LED_EDGE_TYPE NONE
#define LED_FREQ 50000000
#define LED_HAS_IN 0
#define LED_HAS_OUT 1
#define LED_HAS_TRI 0
#define LED_IRQ_TYPE NONE
#define LED_RESET_VALUE 1023


#endif /* _ALTERA_HPS_0_H_ */
